# Generated by Django 6.0.1 on 2026-01-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
