# Generated by Django 6.0.1 on 2026-01-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catogery',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
